### PR TITLE
Add file win1.ring   -  Test for gui lessons

### PR DESCRIPTION
**Pull request by ZAGHTN**
Hello M.Mahmoud.
Is this correct? 🥇

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
Thanks

**Comment by MahmoudFayed** [comment]
Looks good test, I will merge it

**Comment by ZAGHTN** [comment]
> Thanks, If you have any question post it in Ring Group

Okay thank you very much.

**Comment by MahmoudFayed** [comment]
You are welcome

**Pull request merged**
