### PR TITLE
first lesson

### PR DESCRIPTION
**Pull request by AhmedKotby14**

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
I will create a folder and add your file to it.
Then you have to add your next files to this folder.

**Comment by MahmoudFayed** [comment]
Now you have this folder : https://github.com/ring-lang/ring/tree/master/developers/Arabic/Ahmed%20Kotby  

In the future add your files to it.

**Comment by AhmedKotby14** [comment]
What is wrong with this code

**Comment by MahmoudFayed** [comment]
Nothing wrong, I just created a folder with your name so you can add your files to it.
instead of adding it to developers/Arabic
It's added to developers/Arabic/Ahmed Kotby

**Comment by AhmedKotby14** [comment]
Sorry to waste your time but I did these steps and did not work

**Comment by MahmoudFayed** [comment]
1 - login using your GitHub Account
2 - open this project : https://github.com/ring-lang/ring 
3 - You will find in the right (up) three options (Watch - Start - Fork)
4 - Click (Fork) so you can have a copy of the project on your account
5 - Goto your account - to work on your copy of the project
6 - Upload the files to your folder (in your copy) - developers/Arabic/Ahmed Kotby
7 - Then send the pull request
All of these steps are explained in the first video, Just watch it again.

**Pull request merged**
