### PR TITLE
Add lessons

### PR DESCRIPTION
**Pull request by islamderaz**

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
Thanks

**Comment by islamderaz** [comment]
Thanks to you.
There is a file for application for age calculation, could you review it if
you can.

**Comment by MahmoudFayed** [comment]
In this stage, Don't add extra samples outside the course content.
After finishing the course, The team will be asked to develop samples and complete applications
The discussion about these samples will be in Ring Group, Not here in GitHub
Keep up the good work

**Comment by islamderaz** [comment]
Ok, thank you

**Comment by MahmoudFayed** [comment]
You are welcome

**Pull request merged**
