### PR TITLE
Added Ring Highlighting For Vim !!

### PR DESCRIPTION
**Pull request by Programmer-Om**
Hello Mr.Mahmoud , new editor joined our editors family , it's " Vim " .
I have added Ring highlighting for vim , we can now use it simply !!

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
Thanks for your contribution

**Comment by MahmoudFayed** [comment]
Hello Omar

The image is removed
It contains multiple syntax errors
In Ring we use (endif), (endfunction) as one keyword
Also, we use (=) instead of (==) to test the variable value

Thanks

**Comment by Programmer-Om** [comment]
Hi , well I used Gemini Ai for this code , as I think it makes mistakes like chat gpt (It gives me unknown keyword before on JS)
I think Ai isn't yet can be used for development

**Comment by MahmoudFayed** [comment]
Hello
You will find a lot of samples in this folder: https://github.com/ring-lang/ring/tree/master/samples
You can use any of them in the screen shot

**Pull request merged**
