### PR TITLE
RingNotepad: Better integration with built-in Apache webserver to run…

### PR DESCRIPTION
**Pull request by MajdiSobain**
… web apps in nonWindows OS

### CODE REVIEW

**Comment by MajdiSobain** [comment]
Hello Mahmoud

I have done some integration to help run ring web apps from within RingNotepad.
It's been tested in Ubuntu and its working well but need to be tested on Fedora and Mac OS

Have a nice time :)

Greetings
Majdi

**Comment by MajdiSobain** [comment]
Sorry I meant with "built-in" the official builds of apache webserver for the corresponding OSs

**Comment by MahmoudFayed** [comment]
Hello Majdi

Very nice contribution, Thanks for sharing
I will test it 

Greetings,
Mahmoud

**Comment by MajdiSobain** [comment]
Hello Mahmoud

You are welcome

In the future, I will try to add some integration for XAMPP to the scripts then do some documentation.

Greetings
Majdi

**Comment by MahmoudFayed** [comment]
Hello Mansour

Very nice plan, Keep up the GREAT WORK

Greetings,
Mahmoud

**Pull request merged**
