### PR TITLE
Ring Scanner: avoid unnecessary strdup call in ring_scanner_checktoken

### PR DESCRIPTION
**Pull request by idrassi**
This gives a performance boost of 4% on Windows for large ring files

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
Thanks for the update

**Comment by MahmoudFayed** [comment]
I did a little update in this commit : https://github.com/ring-lang/ring/commit/73dbc87ea18375403998cf3ca62b661794c93efa

Since we already test the condition ( pScanner->pRingState->lNotCaseSensitive ) and we have (else) - No need to test (! pScanner->pRingState->lNotCaseSensitive) using another if statement.
Repeating the function call ( ring_hashtable_findnumber() ) is better than repeating the if statement.

**Comment by idrassi** [comment]
Thank you for the update.
Indeed, this is better!

**Comment by MahmoudFayed** [comment]
You are welcome

**Pull request merged**
