### PR TITLE
Factorial Recursion

### PR DESCRIPTION
**Pull request by TawfikYasser**
# Factorial Recursion
Ring GUI application to calculates the factorial using recursion.

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
Thanks
The ring/application folder contains more larger applications
This will be moved to ring/samples/UsingFormDesigner folder

**Comment by TawfikYasser** [comment]
> Thanks
> The ring/application folder contains more larger applications
> This will be moved to ring/samples/general folder

Thanks, i will continuously contribute to Ring, i’m really very interested about it.

**Comment by MahmoudFayed** [comment]
You are welcome

**Comment by MahmoudFayed** [comment]
Your name is added to Ring Team : https://ring-lang.sourceforge.io/team.html 
Keep up the GOOD WORK

**Comment by TawfikYasser** [comment]
> Your name is added to Ring Team : https://ring-lang.sourceforge.io/team.html
> Keep up the GOOD WORK

It's a pleasure to me, thank you.

**Comment by MahmoudFayed** [comment]
You are welcome

**Pull request merged**
