### PR TITLE
Add files of lesson 003

### PR DESCRIPTION
**Pull request by AdelMahmoudHussein**
I want to know How to wait seconds before close the program after saying good bye in file number 016

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
Thanks

**Comment by MahmoudFayed** [comment]
You can use the sleep() function in StdLib
For any questions use the Ring Group

**Comment by AdelMahmoudHussein** [comment]
thank you very much Mr/Mahmoud

**Comment by MahmoudFayed** [comment]
You are welcome

**Pull request merged**
