### PR TITLE
Murmurhash extension

### PR DESCRIPTION
**Pull request by 7snovic**
Implement a full coverage for the Murmur Hash library,

Murmur hash is only used in `openssl` extension with only one function.

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
Very nice work, Just Add
(1) Scripts to build on Windows and macOS too (Ring is portable)
(2) Documentation (or at least README.md file) contains description + examples (from your tests)
(3) Separate Ring file (murmurhashlib.ring) to load the library (so/dylib/dll) based on the operating system

**Comment by 7snovic** [comment]
I may face some troubles with Windows script build as I'm not a windows user, I may write the script but I will not be able to test it.

**Comment by MahmoudFayed** [comment]
No problem, Just write it (Look at similar scripts in other extensions), and I will revise and test it.

**Comment by 7snovic** [comment]
@MahmoudFayed kindly revise the changes.

**Comment by MahmoudFayed** [comment]
Thanks for the update, Keep up the good work.

**Pull request merged**
