### PR TITLE
updating E2 pull request

### PR DESCRIPTION
**Pull request by Ilir-Liburn**
Hello,

I made update, compiling and linking for Mac is now OS version independent. For other systems, Ring compiles and links against OS clock_gettime version.

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
The update has conflicts
(1) Use the current source code files in : https://github.com/ring-lang/ring
(2) Do your updates on these files 
Thanks

**Comment by Ilir-Liburn** [comment]
Done.

**Comment by MahmoudFayed** [comment]
Try this
(1) Create a new fork 
(2) Do the updates to this new fork
(3) Send the pull request
It's not the smart way, but a simple one that works.

**Comment by Ilir-Liburn** [comment]
OK, then I closing this pull request.

**Pull request closed without merging**
