### PR TITLE
FormDesigner : Prevent crash at time of loading due to using (") at time of setting event actions

### PR DESCRIPTION
**Pull request by MajdiSobain**
I found this is easier than changing ( " ) into ( ' ) in ObjectDataAsString functions of all controllers

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
Hello Majdi

Thanks for the report. 

(1) A better way to apply your work around is using substr() 
Where you can replace the the '"' character with any other character

(2) We will not apply this fix, using this way or using substr() because we don't like to hide the bugs.

(3) The user must become able to write " " in properties, The use may need it in label captions for examples.

Greetings,
Mahmoud

**Comment by MahmoudFayed** [comment]
Hello Majdi
I have already fixed the problem, Now we can use " in properties values
Keep up the good work :D 
Greetings,
Mahmoud

**Comment by MajdiSobain** [comment]
Hello Eng. Mahmoud

You are welcome :)

I'm sorry for this prosthetic solution
But at least its used as a bug report ^_^

Thanks for the Fix :D 

Have a nice time

Greetings
Majdi

**Comment by MahmoudFayed** [comment]
Hello Majdi

Thank you very much, Keep up the good work 

Greetings,
Mahmoud

**Pull request closed without merging**
