### PR TITLE
Add lesson 1

### PR DESCRIPTION
**Pull request by Morsi22**

### CODE REVIEW

**Comment by MahmoudFayed** [comment]
Thanks

**Comment by Morsi22** [comment]
I try to upload the projects i applied on githup in my folder but i can't
and this message appears, what should i do?

​

2018-06-20 2:12 GMT+02:00 Mahmoud Samir Fayed <notifications@github.com>:

**Comment by MahmoudFayed** [comment]
(1) Delete your current fork
(2) Fork Again 
(3) Add your files to this folder (In your fork)
https://github.com/ring-lang/ring/tree/master/developers/Arabic/Morsi%20Ashraf
(4) Send a Pull Request

**Comment by Morsi22** [comment]
Will i do these steps every time i wanna add a new file?

**Comment by MahmoudFayed** [comment]
No, You will do step (1) and step (2) Just for this time

Later you will do only step(3) and step(4)

**Pull request merged**
